### PR TITLE
fix: Bad URL formatting and requests for Snyk API calls

### LINKED ISSUE #107: Snyk API calls using bad URL formatting and GET instead of POST
## Overview

I encountered two main issues with testing the Snyk log pullers:

- Bad format strings for URLs
- Using GET requests instead of the required POST requests (w/ req body)

### Bad string formatting

The Snyk audit log puller is calling badly formatted URLs and swallowing errors.

Example URL that was being used:

```
https://api.snyk.io/api/v1/group/2023-01-22/audit?from=2023-02-20&to=SYNK-GROUP-ID-IS-HERE&page=1&sortOrder=ASC
```

(Notice the transposition of the group ID and the `to` query string arg.)

### GET instead of POST requests

All the API calls are using GET requests instead of the required POST requests. The POST requests also require a JSON body for easy requests, to allow passing filters. Even if you want no filters, the API expects you to pass an empty JSON body, or it will fail.

### PR DESCRIPTION
**Pull request by timoguin**
This PR fixes the ordering for the format args for group and org-level audit logs. It also updates each of the API calls to use POST requests, including any necessary request bodies.

## Changed

- Fix URL formatting args for Snyk audit log URLs
- Update Snyk API calls to use POST requests with proper JSON bodies

Fixes #107.

### CODE REVIEW

**Review by Samrose-Ahmed — APPROVED** [review]
LGTM!

**Comment by shaeqahmed** [comment]
SHIP IT! ⛴️

**Review by shaeqahmed — APPROVED** [review]
Looks good to me

**Comment by shaeqahmed** [comment]
Great work. Hey @all-contributors please add @timoguin for code

**Pull request merged**
